Alynos_BioTech_SuperSystem/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("System_App.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

System_App/urls.py
from django.urls import path

from . import views


app_name = "BioTech_App"

urlpatterns = [

    path('', views.index, name="index"),
    path('about/', views.about, name="about"),
    path('appointment/', views.appointment, name="appointment"),
    path('appointment_view/', views.appointment_view, name="appointment_view"),
    path('blog_sidebar/', views.blog_sidebar, name="blog_sidebar"),
    path('blog_single/<int:blog_id>/', views.blog_single, name="blog_single"),
    path('confirmation/', views.confirmation, name="confirmation"),
    path('department/', views.department, name="department"),
    path('department_single/<int:department_id>/', views.department_single, name="department_single"),
    path('doctor/', views.doctor, name="doctor"),
    path('doctor_single/<int:doctor_id>/', views.doctor_single, name="doctor_single"),
    path('contact/', views.contact, name="contact"),
    path('products/', views.product_list, name="product_list"),
    path('product_detail/<int:product_id>/', views.product_detail, name="product_detail"),
    path('view_cart/', views.view_cart, name='view_cart'),
    path('add_cart/<int:product_id>/', views.add_cart, name='add_cart'),
    path('remove_from_cart/<int:item_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('payment/', views.payment_process, name='payment'),
    path('payment_page/', views.payment_page, name='payment_page'),
    path('payment_success/', views.payment_success, name='payment_success'),
    path('payment_failed/', views.payment_failed, name='payment_failed'),
    path('submit_message/', views.submit_message, name='submit_message'),
    path('message_confirmation', views.message_confirmation, name='message_confirmation')
    ]

System_App/views.py
from django.shortcuts import render,redirect, get_object_or_404
from .models import Products, ProductDetail, Doctor, DoctorDetails, Department, DepartmentDetails
# Create your views here.
from django.contrib import messages
# from django.http import JsonResponse
from .models import CartItem, CheckoutForm, Appointment, PaymentReport,Blog, BlogDetail, Comment, Purchase, ContactMessage
import locale
import re
# from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def index(request):
    return render(request, "index.html", {'navbar': 'index'})

def about(request):

   doctors = Doctor.objects.all()

   return render(request, "about.html", {'doctors': doctors, 'navbar': 'about'})

def contact(request):
    return render(request, "contact.html", {'navbar': 'contact'})

def submit_message(request):
    if request.method == 'POST':
        fullname = request.POST.get('fullname')
        email = request.POST.get('email')
        subject = request.POST.get('subject')
        phone = request.POST.get('phone')
        message = request.POST.get('message')

        ContactMessage.objects.create(
            fullname=fullname,
            email=email,
            subject=subject,
            phone=phone,
            message=message
        )

        successive_message = 'Your Message has been sent Successfully!'
        messages.success(request, successive_message)

        return render(request, 'message_confirmation.html', {'success_message': successive_message})

    return redirect('BioTech_App:index')

def message_confirmation(request):

    return render(request, "message_confirmation.html")

def appointment(request):
    return render(request, "appoinment.html", {'navbar': 'contact'})

def department(request):

    departments = Department.objects.all()

    return render(request, "department.html", {'departments': departments, 'navbar': 'department'})

def department_single(request, department_id):

    department = get_object_or_404(Department, pk=department_id)
    details = get_object_or_404(DepartmentDetails, department=department)

    return render(request, "department-single.html", {'department': department, 'details': details, 'navbar': 'department_single'})

def appointment_view(request):
    if request.method == 'POST':
        doctor_name = request.POST.get('doctor')
        department_name = request.POST.get('department')
        date = request.POST.get('date')
        time = request.POST.get('time')
        full_name = request.POST.get('full_name')
        phone_number = request.POST.get('phone_number')
        message = request.POST.get('message')

        # Create Appointment instance without saving to the database
        Appointment.objects.create(
            department_name=department_name,
            doctor_name=doctor_name,
            date=date,
            time=time,
            full_name=full_name,
            phone_number=phone_number,
            message=message
        )

        success_message = 'Appointment booked Successfully.'
        messages.success(request, success_message)

        # Pass the success message to the confirmation page
        return render(request, 'confirmation.html', {'success_message': success_message})

    # Handle cases where the request method is not POST (optional)
    return redirect('BioTech_App:index')

def confirmation(request):
    return render(request, "confirmation.html", {'navbar': 'confirmation'})

def blog_sidebar(request):

    blogs = Blog.objects.all()

    return render(request, "blog-sidebar.html", {'blogs': blogs, 'navbar': 'blog_sidebar'})

def blog_single(request, blog_id):

    blog = get_object_or_404(Blog, id=blog_id)
    blog_detail = get_object_or_404(BlogDetail, blog=blog)

    return render(request, "blog-detail.html", {'blog':blog, 'blog_detail': blog_detail, 'navbar': 'blog_single'})


def comment_section(request, blog_id):

    blog = get_object_or_404(Doctor, id=blog_id)
    comment_detail = get_object_or_404(Comment, blog=blog)

    return render(request, "blog-detail.html", {'blog':blog, 'comment_detail': comment_detail, 'navbar': 'blog_single'})

def checkout(request):
    locale.setlocale(locale.LC_ALL, '')

    cart_summary = request.GET.get('cart_summary', None)
    cart = request.session.get('cart', [])

    # Convert the session cart data to a list of CartItem instances
    cart_items = [
        CartItem(
            product_id=item['product_id'],
            quantity=item['quantity'],
            title=item['title'],
            price=item['price']
        )
        for item in cart
    ]

    # Calculate total_price
    total_price = sum(item.price * item.quantity for item in cart_items)

    formatted_total_price = locale.currency (total_price, grouping=True)

    # Pass the cart_items and cart_summary to the template
    return render(request, 'sales/checkout.html',
                  {'cart_items': cart_items, 'cart_summary': cart_summary, 'total_price': formatted_total_price})

def doctor(request):

    doctors = Doctor.objects.all()

    return render(request, "doctors/doctor.html", {'doctors': doctors, 'navbar': 'doctor'})

def doctor_single(request, doctor_id):

    doctor = get_object_or_404(Doctor, id=doctor_id)
    details = get_object_or_404(DoctorDetails, doctor=doctor)

    return render(request, "doctors/doctor-single.html", {'doctor': doctor, 'details': details, 'navbar': 'doctor_single'})


def product_list(request):

    products = Products.objects.all()

    return render(request, "sales/products.html", {'products': products, 'navbar': products})

def product_detail(request, product_id):

    product = get_object_or_404(Products, id=product_id)
    product_detail = get_object_or_404(ProductDetail, product=product)


    return render(request, 'sales/product_detail.html',{'product': product, 'product_detail': product_detail})

# Pass the cart_items to the template

def add_cart(request, product_id):
    product = get_object_or_404(Products, id=product_id)
    quantity = int(request.POST.get('quantity', 1))  # Ensure quantity is an integer

    # Convert Decimal to float for JSON serialization
    price = float(product.price)

    cart = request.session.get('cart', [])

    # Check if the item is already in the cart
    for item in cart:
        if item['product_id'] == product.id:
            item['quantity'] += quantity
            break
    else:
        # If not, add it to the cart
        cart_item = CartItem(
            product_id=product.id,
            quantity=quantity,
            title=product.title,
            price=price
        )
        cart.append(cart_item.__dict__)

    request.session['cart'] = cart

    messages.success(request, 'Item Added to cart successfully.')


    return redirect('BioTech_App:view_cart')


def view_cart(request):
    # Set the locale to the user's default locale
    locale.setlocale(locale.LC_ALL, '')

    cart = request.session.get('cart', [])

    # Convert product_id to Products object in each cart item
    cart_items = []
    total_price = 0

    for item in cart:
        product_id = item.get('product_id')
        quantity = item.get('quantity', 0)
        title = item.get('title')
        price = item.get('price', 0)

        # Fetch the corresponding Products object
        try:
            product = Products.objects.get(id=product_id)
        except Products.DoesNotExist:
            # Handle the case where the product with the given ID is not found
            product = None

        # Ensure that price and quantity are valid numbers
        try:
            price = float(price)
            quantity = int(quantity)
        except (ValueError, TypeError):
            # Handle the case where price or quantity is not a valid number
            price = 0
            quantity = 0

        # Create the CartItem instance
        cart_item = CartItem(product_id=product_id, quantity=quantity, title=title, price=price)
        cart_items.append(cart_item)

        # Calculate the total price
        total_price += price * quantity

    # Format the total price as currency
    formatted_total_price = locale.currency(total_price, grouping=True)

    context = {
        'navbar':'view_cart',
        'cart': cart_items,
        'total_price': formatted_total_price,
    }

    return render(request, 'sales/view_cart.html', context)


def remove_from_cart(request, item_id):
    cart = request.session.get('cart', [])

    # Find the index of the item with the specified ID
    item_index = next((index for (index, item) in enumerate(cart) if item['product_id'] == item_id), None)

    if item_index is not None:
        # Remove the item from the cart
        del cart[item_index]
        request.session['cart'] = cart

        messages.success(request, 'Selected item has been removed from cart.')

    return redirect('BioTech_App:view_cart')


def payment_page(request):
    if request.method == 'POST':
        fname = request.POST.get('fname')
        lname = request.POST.get('lname')
        address = request.POST.get('address')
        address2 = request.POST.get('address2')
        email = request.POST.get('email')
        phone = request.POST.get('phone')
        messageinfo = request.POST.get('messageinfo')

        checkout_form = CheckoutForm.objects.create(
            fname=fname,
            lname=lname,
            address=address,
            address2=address2,
            email=email,
            phone=phone,
            messageinfo=messageinfo
        )

        cart = request.session.get('cart', [])

        for item in cart:
            product_id = item['product_id']
            quantity = item['quantity']

            # Retrieve the corresponding Product instance
            product = Products.objects.get(id=product_id)

            # Create a Purchase record
            Purchase.objects.create(
                checkout_form=checkout_form,
                product=product,
                quantity=quantity
            )

System_App/templates/confirmation.html
{% extends 'layout.html' %}

{% load static %}

{% block body %}

<section class="section confirmation">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-8">
          <div class="confirmation-content text-center">
            <i class="icofont-check-circled text-lg text-color-2"></i>
              <h2 class="mt-3 mb-4">Thank you for your appointment</h2>
              {% if messages %}
                {% for message in messages %}
                  <p class="alert alert-success">{{ message }}</p>
                {% endfor %}
              {% endif %}
              <p>We will contact you soon.</p>
           <a href="{% url 'BioTech_App:index' %}" class="btn btn-main-2 btn-round-full">Back To HomePage<i class="icofont-simple-right ml-2"></i></a>
          </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}

System_App/templates/department-single.html
{%extends 'layout.html' %}

{% load static %}

{% block body %}

<section class="page-title bg-1">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="block text-center">
          <span class="text-white">Department Details</span>
          <h1 class="text-capitalize mb-5 text-lg">{{ department.name}}</h1>

          <!-- <ul class="list-inline breadcumb-nav">
            <li class="list-inline-item"><a href="index.html" class="text-white">Home</a></li>
            <li class="list-inline-item"><span class="text-white">/</span></li>
            <li class="list-inline-item"><a href="#" class="text-white-50">Department Details</a></li>
          </ul> -->
        </div>
      </div>
    </div>
  </div>
</section>


<section class="section department-single">
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<div class="department-img">
					<img src="{{details.image.url}}" alt="{{ department.name }} Image" class="img-fluid">
				</div>
			</div>
		</div>

		<div class="row">
			<div class="col-lg-8">
				<div class="department-content mt-5">
					<h3 class="text-md">{{ department.name}}</h3>
					<div class="divider my-4"></div>
					<p class="lead">{{ details.description1}}</p>
                    <p>{{ details.description2}}</p>

					<h3 class="mt-5 mb-4">Services features</h3>
					<div class="divider my-4"></div>
					<ul class="list-unstyled department-service">
						<li><i class="icofont-check mr-2"></i>{{ details.service_feature1}}</li>
						<li><i class="icofont-check mr-2"></i>{{ details.service_feature2}}</li>
						<li><i class="icofont-check mr-2"></i>{{ details.service_feature3}}</li>
						<li><i class="icofont-check mr-2"></i>{{ details.service_feature4}}</li>
						<li><i class="icofont-check mr-2"></i>{{ details.service_feature5}}</li>
						<li><i class="icofont-check mr-2"></i>{{ details.service_feature6}}</li>
					</ul>

					<a href="{% url 'BioTech_App:appointment' %}" class="btn btn-main-2 btn-round-full">Make an Appointment<i class="icofont-simple-right ml-2  "></i></a>
                    <p></p>
                    <a href="{% url 'BioTech_App:doctor' %}" class="btn btn-main-2 btn-round-full">View Our Doctors<i class="icofont-simple-right ml-2"></i></a>
				</div>
			</div>

			<div class="col-lg-4">
				<div class="sidebar-widget schedule-widget mt-5">
					<h5 class="mb-4">Time Schedule</h5>

					<ul class="list-unstyled">
					  <li class="d-flex justify-content-between align-items-center">
					    <a href="#">Monday - Friday</a>
					    <span>9:00 - 17:00</span>
					  </li>
					  <li class="d-flex justify-content-between align-items-center">
					    <a href="#">Saturday</a>
					    <span>9:00 - 16:00</span>
					  </li>
					  <li class="d-flex justify-content-between align-items-center">
					    <a href="#">Sunday</a>
					    <span>Closed</span>
					  </li>
					</ul>

					<div class="sidebar-contatct-info mt-4">
						<p class="mb-0">Need Urgent Help?</p>
						<h3>+254-765-657 905</h3>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

{% endblock %}

System_App/templates/department.html
{%extends 'layout.html' %}

{% load static %}

{% block body %}

<section class="page-title bg-1">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="block text-center">
          <span class="text-white">All Department</span>
          <h1 class="text-capitalize mb-5 text-lg">Our Services'-Departments</h1>

          <!-- <ul class="list-inline breadcumb-nav">
            <li class="list-inline-item"><a href="index.html" class="text-white">Home</a></li>
            <li class="list-inline-item"><span class="text-white">/</span></li>
            <li class="list-inline-item"><a href="#" class="text-white-50">All Department</a></li>
          </ul> -->
        </div>
      </div>
    </div>
  </div>
</section>


<section class="section service-2">
	<div class="container">
		<div class="row justify-content-center">
			<div class="col-lg-7 text-center">
				<div class="section-title">
					<h2>Award-winning patient care</h2>
					<div class="divider mx-auto my-4"></div>
					<p>Alynos is dedicated to providing a comprehensive range of high-quality services in the field of healthcare and biotechnology.
                        Our commitment is centered around delivering innovative solutions and cutting-edge technologies to enhance patient care, research, and medical advancements.
                        Below is an overview of the key services offered by Alynos-Kenya:</p>
				</div>
			</div>
		</div>

		<div class="row">
            {% for department in departments %}
			<div class="col-lg-4 col-md-6 ">
				<div class="department-block mb-5">
					<img src="{{department.image.url}}" alt="{{ department.name }} Image" class="img-fluid w-100">
					<div class="content">
						<h4 class="mt-4 mb-2 title-color">{{ department.name }}</h4>
						<p class="mb-4">{{ department.description}}.</p>
						<a href="{% url 'BioTech_App:department_single' department.id %}" class="read-more">Learn More  <i class="icofont-simple-right ml-2"></i></a>
					</div>
				</div>
			</div>
            {% endfor %}

		</div>
	</div>
</section>

{% endblock %}

System_App/templates/layout.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <meta name="description" content="Orbitor,business,company,agency,modern,bootstrap4,tech,software">
  <meta name="author" content="themefisher.com">

  <title>Alynos- Health & Care Medical template</title>

  <!-- Favicon -->
  <link rel="shortcut icon" type="image/x-icon" href="{% static '/images/favicon.ico' %}" />

  <!-- bootstrap.min css -->
  <link rel="stylesheet" href="{% static 'plugins/bootstrap/css/bootstrap.min.css' %}">
  <!-- Icon Font Css -->
  <link rel="stylesheet" href="{% static 'plugins/icofont/icofont.min.css' %}">
  <!-- Slick Slider  CSS -->
  <link rel="stylesheet" href="{% static 'plugins/slick-carousel/slick/slick.css' %}">
  <link rel="stylesheet" href="{% static 'plugins/slick-carousel/slick/slick-theme.css' %}">

  <!-- Main Stylesheet -->
  <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>

<body id="top">

<header>
	<div class="header-top-bar">
		<div class="container">
			<div class="row align-items-center">
				<div class="col-lg-6">
					<ul class="top-bar-info list-inline-item pl-0 mb-0">
						<li class="list-inline-item"><a href="mailto:support@gmail.com"><i class="icofont-support-faq mr-2"></i>support@alynos.com</a></li>
						<li class="list-inline-item"><i class="icofont-location-pin mr-2"></i>Address 32-East-Drive, Westlands, Nairobi-Kenya </li>
					</ul>
				</div>
				<div class="col-lg-6">
					<div class="text-lg-right top-right-bar mt-2 mt-lg-0">
						<a href="tel:+254-789-678 905``
.   -.
.1..." >
							<span>Call Now : </span>
							<span class="h4">+254 789 678 905</span>
						</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<nav class="navbar navbar-expand-lg navigation, ml-4" id="navbar">
		<div class="container">
		 	 <a class="navbar-brand" href="{% url 'BioTech_App:index' %}">
			  	<img src="{% static 'images/logo_02.png' %}" alt="" class="img-fluid">
			  </a>
        <p><br> BioTechnologies <br> Limited </p>

		  	<button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarmain" aria-controls="navbarmain" aria-expanded="false" aria-label="Toggle navigation">
			<span class="icofont-navigation-menu"></span>
		  </button>

		  <div class="collapse navbar-collapse" id="navbarmain">
			<ul class="navbar-nav ml-auto">
			  <li class="nav-item {% if navbar == 'index' %}active{% endif %}"><a class="nav-link" href="{% url 'BioTech_App:index' %}">Home</a></li>
			   <li class="nav-item {% if navbar == 'about' %}active{% endif %}"><a class="nav-link" href="{% url 'BioTech_App:about' %}">About</a></li>
			    <li class="nav-item {% if navbar == 'products' %}active{% endif %}"><a class="nav-link" href="{% url 'BioTech_App:product_list' %}">Products</a></li>

			    <li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="{% url 'BioTech_App:department' %}" id="dropdown02" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Department <i class="icofont-thin-down"></i></a>
					<ul class="dropdown-menu" aria-labelledby="dropdown02">
						<li><a class="dropdown-item {% if navbar == 'department' %}active{% endif %}" href="{% url 'BioTech_App:department' %}">Departments</a></li>
						<li><a class="dropdown-item {% if navbar == 'department_single' %}active{% endif %}" href="{% url 'BioTech_App:department_single' department_id=1 %}">Department Detailing</a></li>
					</ul>
			  	</li>

			  	<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="{% url 'BioTech_App:doctor' %}" id="dropdown03" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Doctors <i class="icofont-thin-down"></i></a>
					<ul class="dropdown-menu" aria-labelledby="dropdown03">
						<li><a class="dropdown-item {% if navbar == 'doctor' %}active{% endif %}" href="{% url 'BioTech_App:doctor' %}">Doctors</a></li>
						<li><a class="dropdown-item {% if navbar == 'doctor_single' %}active{% endif %}" href="{% url 'BioTech_App:doctor_single' doctor_id=1 %}">Doctor Detailing</a></li>
						<li><a class="dropdown-item {% if navbar == 'appointment' %}active{% endif %}" href="{% url 'BioTech_App:appointment' %}">Appointment</a></li>
					</ul>
			  	</li>

			   <li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="{% url 'BioTech_App:blog_sidebar' %}" id="dropdown05" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Blog <i class="icofont-thin-down"></i></a>
					<ul class="dropdown-menu" aria-labelledby="dropdown05">
						<li><a class="dropdown-item {% if navbar == 'blog_sidebar' %}active{% endif %}" href="{% url 'BioTech_App:blog_sidebar' %}">Blog Page</a></li>

						<li><a class="dropdown-item {% if navbar == 'blog_single' %}active{% endif %}" href="{% url 'BioTech_App:blog_single' blog_id=1 %}">Blog Detailing</a></li>
					</ul>
			  	</li>
			   <li class="nav-item {% if navbar == 'contact' %}active{% endif %}"><a class="nav-link" href="{% url 'BioTech_App:contact' %}">Contact</a></li>
                <li class="nav-item {% if navbar == 'view_cart' %}active{% endif %}"><a class="nav-link" href="{% url 'BioTech_App:view_cart' %}">Cart</a></li>
			</ul>
		  </div>
		</div>
	</nav>
</header>


        {% block body %}
        {% endblock %}


<footer class="footer section gray-bg">
	<div class="container">
		<div class="row">
			<div class="col-lg-4 mr-auto col-sm-6">
				<div class="widget mb-5 mb-lg-0">
					<div class="logo mb-4">
						<img src="{% static 'images/logo_02.png' %}" alt="Alynos BioTech Logo" class="img-fluid">
					</div>
					<p>At Alynos BioTech, we are committed to providing innovative healthcare solutions. Our mission is to enhance lives through cutting-edge technology and compassionate care.</p>

					<ul class="list-inline footer-socials mt-4">
						<li class="list-inline-item"><a href="https://www.facebook.com/alynosbiotech"><i class="icofont-facebook"></i></a></li>
						<li class="list-inline-item"><a href="https://twitter.com/alynosbiotech"><i class="icofont-twitter"></i></a></li>
						<li class="list-inline-item"><a href="https://www.linkedin.com/company/alynosbiotech/"><i class="icofont-linkedin"></i></a></li>
					</ul>
				</div>
			</div>

			<div class="col-lg-2 col-md-6 col-sm-6">
				<div class="widget mb-5 mb-lg-0">
					<h4 class="text-capitalize mb-3">Department</h4>
					<div class="divider mb-4"></div>

					<ul class="list-unstyled footer-menu lh-35">
						<li><a href="{% url 'BioTech_App:department_single' department_id=1 %}">Examination And Diagnosis </a></li>
						<li><a href="{% url 'BioTech_App:department_single' department_id=4 %}">Medicine And Health</a></li>
						<li><a href="{% url 'BioTech_App:department_single' department_id=7 %}">Radiology</a></li>
						<li><a href="{% url 'BioTech_App:department_single' department_id=2 %}">Cardiology</a></li>
						<li><a href="{% url 'BioTech_App:department_single' department_id=6 %}">Paediatrics</a></li>
					</ul>
				</div>
			</div>

			<div class="col-lg-2 col-md-6 col-sm-6">
				<div class="widget mb-5 mb-lg-0">
					<h4 class="text-capitalize mb-3">Support</h4>
					<div class="divider mb-4"></div>

					<ul class="list-unstyled footer-menu lh-35">
						<li><a href="{% url 'BioTech_App:about' %}">About Us</a></li>
						<li><a href="{% url 'BioTech_App:product_list'%}">Products</a></li>
						<li><a href="{% url 'BioTech_App:department'%}">Departments </a></li>
						<li><a href="{% url 'BioTech_App:blog_sidebar'%}">Our Blog</a></li>
						<li><a href="{% url 'BioTech_App:appointment'%}">Make Appointment</a></li>
					</ul>
				</div>
			</div>

			<div class="col-lg-3 col-md-6 col-sm-6">
				<div class="widget widget-contact mb-5 mb-lg-0">
					<h4 class="text-capitalize mb-3">Get in Touch</h4>
					<div class="divider mb-4"></div>

					<div class="footer-contact-block mb-4">
						<div class="icon d-flex align-items-center">
							<i class="icofont-email mr-3"></i>
							<span class="h6 mb-0">Support Available for 24/7</span>
						</div>
						<h4 class="mt-2"><a href="mailto:alynos@gmail.com">alynos@gmail.com</a></h4>
					</div>

					<div class="footer-contact-block">
						<div class="icon d-flex align-items-center">
							<i class="icofont-support mr-3"></i>
							<span class="h6 mb-0">Mon to Fri : 08:30 - 18:00</span>
						</div>
						<h4 class="mt-2"><a href="tel:+254-789-678 905">+254-789-678 905</a></h4>
					</div>
				</div>
			</div>
		</div>

		<div class="footer-btm py-4 mt-5">
			<div class="row align-items-center justify-content-between">
				<div class="col-lg-6">
					<div class="copyright">
						&copy; Copyright Reserved to <span class="text-color">Alynos Medical Dept.</span>
					</div>
				</div>

			</div>

			<div class="row">
				<div class="col-lg-4">
					<a class="backtop js-scroll-trigger" href="#top">
						<i class="icofont-long-arrow-up"></i>
					</a>
				</div>
			</div>
		</div>
	</div>
</footer>


 <!--
    Essential Scripts
    =====================================-->


    <!-- Main jQuery -->
    <script src="{% static 'plugins/jquery/jquery.js' %}"></script>
    <!-- Bootstrap 4.3.2 -->
    <script src="{% static 'plugins/bootstrap/js/popper.js' %}"></script>
    <script src="{% static 'plugins/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'plugins/counterup/jquery.easing.js' %}"></script>
    <!-- Slick Slider -->
    <script src="{% static 'plugins/slick-carousel/slick/slick.min.js' %}"></script>
    <!-- Counterup -->
    <script src="{% static 'plugins/counterup/jquery.waypoints.min.js' %}"></script>

    <script src="{% static 'plugins/shuffle/shuffle.min.js' %}"></script>
    <script src="{% static 'plugins/counterup/jquery.counterup.min.js' %}"></script>
    <!-- Google Map -->
    <script src="{% static 'plugins/google-map/map.js' %}"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAkeLMlsiwzp6b3Gnaxd86lvakimwGA6UA&callback=initMap"></script>

    <script src="{% static 'js/script.js' %}"></script>
    <script src="{% static 'js/contact.js' %}"></script>

  </body>

  </html>